### ISSUE TITLE
프로젝트 구조 개선

### ISSUE THREAD

**Issue by nijesmik** [nijesmik/ft_irc#31]
# To-do
- [x] `SessionService`와 `ChatService`를 `SessionRepository`와 `ConnectionService`로 구조 개선
- [ ] `ChannelService`에 `Session` 객체를 포인터로 전달
- [x] PART : `findJoinedChannel()` 삭제
- [x] MODE : `getModeInfo()` -> `displayMode(Session &)`
- [x] MODE : `mode()` -> `setMode()`
- [ ] JOIN : channel 추가
