### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by nijesmik** [nijesmik/ft_irc#45]
# To-do
- [x] quit : segmentation fault 수정
- [x] part : segmentation fault 수정
- [x] mode : user mode 무시
